"""empty message

Revision ID: 62857fe9f86a
Revises: ba67ea4f22cc
Create Date: 2016-08-20 16:11:59.567323

"""

# revision identifiers, used by Alembic.
revision = '62857fe9f86a'
down_revision = 'ba67ea4f22cc'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('current_action', sa.String(), nullable=True))
    op.add_column('user', sa.Column('current_action_eror_count', sa.Integer(), nullable=True))
    op.add_column('user', sa.Column('current_scope', sa.String(), nullable=True))
    op.add_column('user', sa.Column('current_scope_eror_count', sa.Integer(), nullable=True))
    op.add_column('user', sa.Column('sent_to_velocify', sa.Boolean(), nullable=True))
    op.add_column('user', sa.Column('total_error_count', sa.Integer(), nullable=True))
    op.drop_column('user', 'error_count')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('error_count', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('user', 'total_error_count')
    op.drop_column('user', 'sent_to_velocify')
    op.drop_column('user', 'current_scope_eror_count')
    op.drop_column('user', 'current_scope')
    op.drop_column('user', 'current_action_eror_count')
    op.drop_column('user', 'current_action')
    ### end Alembic commands ###
