"""empty message

Revision ID: 892794a8a06f
Revises: 62857fe9f86a
Create Date: 2016-08-20 16:13:14.269509

"""

# revision identifiers, used by Alembic.
revision = '892794a8a06f'
down_revision = '62857fe9f86a'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('current_prompt', sa.String(), nullable=True))
    op.add_column('user', sa.Column('current_prompt_eror_count', sa.Integer(), nullable=True))
    op.drop_column('user', 'current_action_eror_count')
    op.drop_column('user', 'current_action')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('current_action', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('user', sa.Column('current_action_eror_count', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('user', 'current_prompt_eror_count')
    op.drop_column('user', 'current_prompt')
    ### end Alembic commands ###
