"""empty message

Revision ID: ba67ea4f22cc
Revises: be19717a34c0
Create Date: 2016-08-19 15:40:20.376716

"""

# revision identifiers, used by Alembic.
revision = 'ba67ea4f22cc'
down_revision = 'be19717a34c0'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('error_count', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'error_count')
    ### end Alembic commands ###
